---
- name: Create volumes on PowerStore and map volumes to host
  hosts: all 
  gather_facts: false
  vars_files:
    - ps_vars.yml
  vars:
  tasks:
    - name: Create volumes on PowerStore
      dellemc_powerstore_volume:
        array_ip: "{{ array_ip }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        vol_name: "{{ item.volname }}"
        size: "{{ item.volsize }}"
        cap_unit: "{{ item.volcapunit }}"
        state: present
        description: "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
        protection_policy: "{{ item.protpolicy }}"
        performance_policy: "{{ item.volperfpol }}"
      register: result_vol    
      loop: "{{ volumes }}"
      loop_control:
        label: "{{ item.volname }} {{ item.volsize }}{{ item.volcapunit }}"
      delegate_to: localhost
      when: volumes is defined

    - name: Map volumes to hosts using host name
      dellemc_powerstore_volume:
        array_ip: "{{ array_ip }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        vol_name: "{{ item.volname }}"
        host: "{{ inventory_hostname }}-{{ item.storage_protocol }}"
        mapping_state: mapped
        state: present
      loop: "{{ map_volumes }}"
      loop_control:
        label: "{{ item.volname }} {{ item.storage_protocol }}"
      delegate_to: localhost
