---
- name: Health Check
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/connection.yml
    - vars/credentials.yml

  tasks:
    - name: Get Health Check
      uri:
        url: "https://{{ unispherehost }}:8443/univmax/restapi/91/system/symmetrix/{{ serial_no }}/health"
        validate_certs: false
        user: "{{ user }}"
        password: "{{ password }}"
        headers:
          Content-Type: "application/json"
        method: GET
        body_format: json
        status_code:
          - 200
      register: response

    - debug:
        var: response
