---

- name: Check existing multipath.conf
  stat:
    path: '/etc/multipath.conf'
  register: exist

- name: "Install Multipath configuration"
  copy:
    src: "{{ role_path }}/files/multipath.conf"
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: 0644
  register: multipathconf
  when: 
    - exist.stat.exists == false

- name: "Update Multipath configuration"
  blockinfile:
    path: /etc/multipath.conf
    create: no
    backup: yes
    insertafter: "^devices {"
    block: |2
            device {
                vendor "DellEMC"
                product "PowerStore"
                path_selector "queue-length 0"
                rr_min_io_rq 1
                path_grouping_policy "group_by_prio"
                prio "alua"
                path_checker "tur"
                failback immediate
                fast_io_fail_tmo 15
            }

            device {
                vendor "COMPELNT"
                product "Compellent Vol"
                path_grouping_policy "group_by_prio"
                path_checker "tur"
                features "0"
                hardware_handler "1 alua"
                prio alua
                failback immediate
                rr_weight uniform
                no_path_retry 24
            }
  when:
    - exist.stat.exists == true

- debug:
    var: multipathconf

- name: 'restart multipathd'
  service:
    name: multipathd
    state: restarted
  when: 
  - multipathconf.changed 



