---
# Provision a Test Dev Setup from Snapshot of production
- name: Provisioning a test environment from source SG for Powermax
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/connection.yml
    - vars/credentials.yml
    - vars/host_storage_details.yml
  vars:
    src_sg_name: "{{ sg_name }}"
    test_sg_name: "{{ sg_name + '_LNKSG2' }}"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  collections:
    - dellemc.powermax

  tasks:
   - debug:
       var: test_sg_name 
  
   - name: Create a Snapshot for a Storage Group
     dellemc.powermax.snapshot:
        <<: *uni_connection_vars
        sg_name: "{{ src_sg_name }}"
        snapshot_name: "ansible_sg_snap"
        ttl: "1"
        ttl_unit: "days"
        state: "present"
     register: snapdetails

   - name: Set Snapid fact
     set_fact:
       snapshot_id: "{{ snapdetails.sg_snap_details.snapid }}"
       cacheable: False 

   - name: Change Snapshot Link Status to Linked
     dellemc.powermax.snapshot:
       <<: *uni_connection_vars
       sg_name: "{{ src_sg_name }}"
       snapshot_name: "ansible_sg_snap"
       snapshot_id: "{{ snapshot_id }}"
       target_sg_name: "{{ test_sg_name }}"
       link_status: "linked"
       state: "present"

