---
# Provision a Test Dev Setup from Snapshot of production
- name: Deletes previously created test environment removing storage groups snapsots and volumes created for the test.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/connection.yml
    - vars/credentials.yml
    - vars/host_storage_details.yml
  vars:
    src_sg_name: "{{ sg_name }}"
    test_sg_name: "{{ sg_name + '_LNKSG' }}"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  collections:
    - dellemc.powermax

  tasks:
    - name: Get all Generations of Snapshot for a Storage Group
      dellemc.powermax.snapshot:
        <<: *uni_connection_vars
        sg_name: "{{ src_sg_name }}"
        snapshot_name: "ansible_sg_snap"
        state: "present"
      register: snap_details
   
    - set_fact:
        snap_generations: "{{ snap_details.sg_snap_details | reverse | list }}"

    - name: unlink Snapshot
      dellemc.powermax.snapshot:
        <<: *uni_connection_vars
        sg_name: "{{ src_sg_name }}"
        snapshot_name: "ansible_sg_snap"
        snapshot_id: "{{ item.snapid }}"
        target_sg_name: "{{ test_sg_name }}"
        link_status: "unlinked"
        state: "present"
      loop: "{{ snap_generations}}"

    - name: Delete Snapshots
      dellemc.powermax.snapshot:
        <<: *uni_connection_vars
        sg_name: "{{ src_sg_name }}"
        snapshot_name: "ansible_sg_snap"
        snapshot_id: "{{ item.snapid }}"  
        target_sg_name: "{{ test_sg_name }}"
        state: "absent"
      loop: "{{ snap_generations }}"

    - name: Get Storage Group Details for {{ test_sg_name }}
      register: storage_details
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ test_sg_name }}"
        service_level: "Diamond"
        state: 'present'

    - name: Delete {{ test_sg_name}} Storage group
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ test_sg_name }}"
        service_level: "Diamond"
        srp: "SRP_1"
        state: 'absent'

    - set_fact:
        all_volumes_Id: "{{storage_details.storage_group_volumes | list}}"

    - name: Delete all the volumes for {{ test_sg_name }}
      dellemc.powermax.volume:
        <<: *uni_connection_vars
        vol_id: "{{item}}"
        state: 'absent'
      loop: "{{ all_volumes_Id}}"


