host1_name: Ansible_Cluster_Host1_IG
host2_name: Ansible_Cluster_Host2_IG
hostgroup_name: Ansible_Cluster_IG

# Host Initiators

host1_initiators:
  - 10000000c98ffaee
  - 10000000c98ffaef

host2_initiators:
  - 10000000c98ffffe
  - 10000000c98ffafe

