#!/usr/bin/env ansible-playbook
---
- name: Cleanup the Storage Deleting Hosts, Volumes and Mappings
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
      - vars/connection.yml
      - vars/credentials.yml
      - vars/cluster_hosts.yml

  vars:
    input: &connection_vars
      password: "{{ password }}"
      array_ip: "{{ array_ip_1 }}"
      user: "{{  user  }}"
      verifycert: false
    vol_name: 'ansible_'
    cap_unit: 'GB'

  tasks:
    - name: Unmap volume from host group 
      dellemc_powerstore_volume:
        <<: *connection_vars
        vol_name: "{{vol_name +'_' }}{{item}}"
        state: 'present'
        mapping_state: 'unmapped'
        hostgroup: "{{ hostgroup_name }}"
      loop: "{{ range(1, 5 + 1, 1) | list }}"

    - name: Delete volume
      dellemc_powerstore_volume:
        <<: *connection_vars
        vol_name: "{{vol_name +'_' }}{{item}}"
        size: 1
        cap_unit: "{{cap_unit}}"
        state: 'absent'
      loop: "{{ range(1, 5 + 1, 1) | list }}"

    - name: Delete host group with hosts using host name
      dellemc_powerstore_hostgroup:
        <<: *connection_vars
        hostgroup_name: "{{ hostgroup_name }}"
        hosts:
          - "{{ host2_name }}"
          - "{{ host1_name }}"
        state: 'absent'
        host_state: 'present-in-group'

    - name: Delete host  {{ host1_name }}
      dellemc_powerstore_host:
        <<: *connection_vars
        host_name: "{{ host1_name }}"
        os_type: 'Linux'
        initiators: "{{ host1_initiators }}"
        state: 'absent'
        initiator_state: 'present-in-host'
      
    - name: Delete host  {{ host2_name }}
      dellemc_powerstore_host:
        <<: *connection_vars
        host_name: "{{ host2_name }}"
        os_type: 'Linux'
        initiators: "{{ host2_initiators }}"
        state: 'absent'
        initiator_state: 'present-in-host'

