---
- name: Storage Pool Module Operations on PowerFlex
  hosts: localhost
  connection: local
  vars:
    gateway_host: '1.2.3.4'
    port: '443'
    verifycert: False
    username: 'user'
    password: 'password'
    pool_name: "ansible_test_pool6"
    protection_domain_name: "domain1"

  collections:
    - dellemc.powerflex
  tasks:

    - name: Create a new Storage pool
      register: result
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_name: "{{pool_name}}"
        protection_domain_name: "{{protection_domain_name}}"
        media_type: "HDD"
        state: "present"

    - name: Create a new Storage pool (Idempotency case)
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_name: "{{pool_name}}"
        protection_domain_name: "{{protection_domain_name}}"
        media_type: "HDD"
        state: "present"

    - name: Set pool id
      set_fact:
        pool_id: "{{result.storage_pool_details.id}}"

    - name: Rename Storage pool by id
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_id: "{{pool_id}}"
        storage_pool_new_name: "new_ansible_pool"
        state: "present"

    - name: Rename Storage pool by id (Idempotency case)
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_id: "{{pool_id}}"
        storage_pool_new_name: "new_ansible_pool"
        state: "present"

    - name: Restore the name of Storage pool by id
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_id: "{{pool_id}}"
        storage_pool_new_name: "{{pool_name}}"
        state: "present"


    - name: Modify a Storage pool by name
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_name: "ansible_test_pool"
        protection_domain_name: "{{protection_domain_name}}"
        use_rmcache: True
        use_rfcache: True
        state: "present"

    - name: Modify a Storage pool by name (Idempotency case)
      dellemc_powerflex_storagepool:
        gateway_host: "{{gateway_host}}"
        username: "{{username}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        storage_pool_name: "ansible_test_pool"
        protection_domain_name: "{{protection_domain_name}}"
        use_rmcache: True
        use_rfcache: True
        state: "present"
