---
- name: ECS create users from specified vars file
  hosts: Dell_EMC_ECS
  gather_facts: true ### True required to save ansible_date_time variable
  vars:
    ###################################################################################################
    DateTimeStamp: "{{ansible_date_time.date}}.{{ansible_date_time.time}}" ### get date & time
    logHost: "localhost" ### log file destination host
    ###################################################################################################
   
    ###################################################################################################
    ##### PHYSICAL ECS EXAMPLE ##### EDITED BELOW VARIBLES TO SUIT YOUR ENVIRONMENT ###################
    ###################################################################################################
    ##### EDITED BELOW VARIBLES TO SUIT YOUR ENVIRONMENT #####
    logFile: "/tmp/ECS_Create_User.{{ DateTimeStamp }}.log" ### DateTimeStamp appended to log file name
    username: "" ### E.g. "root"
    password: "" ### E.g. "ChangeMe"
    ECS_host: "" ### E.g. "192.168.2.21:4443"
    nameSpace: "" ### Add your ECS NameSpace
    UsersFileList: ./ECScreateObjUsersFromList.txt ### Example, file containing list of users to create
    secretKey: "" ### leave blank to automatically generate secret keys
    ###################################################################################################

  tasks:

  - name: Get ECS API authentication token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
    no_log: True

  - name: Connect to ECS | create new Object Users in NameSpace "{{ nameSpace }}"
    uri:
      validate_certs: no
      url: https://{{ECS_host}}/object/users.json
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      body_format: json
      body:
        {
          user: "{{ item }}",
          namespace: "{{ nameSpace }}"
        }
      return_content: yes
    register: results_CreateObjUser
    changed_when: results_CreateObjUser.status == 200
    failed_when: false
    loop: "{{ lookup('file', UsersFileList).splitlines() }}"

  #- debug:
  #    var: results_CreateObjUser

  - name: Connect to ECS | add secret key to previously created users in NameSpace "{{ nameSpace }}"
    uri:
      validate_certs: no
      url: "https://{{ECS_host}}/object/user-secret-keys/{{ item }}"
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      body_format: json
      body:
        {
          namespace: "{{ nameSpace }}",
          secretkey: "{{secretKey }}"
        }
      return_content: yes
    register: results_CreateSecretKey
    changed_when: results_CreateSecretKey.status == 200
    failed_when: false
    loop: "{{ lookup('file', UsersFileList).splitlines() }}"
    notify: userlist

  #- debug:
  #    var: results_CreateSecretKey

  - name: execute ansible handlers
    meta: flush_handlers
  
  - name: Logout ECS API token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      #url: https://{{ECS_host}}/logout?force=true
      url: https://{{ECS_host}}/logout
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      return_content: yes
    register: results_logout
    no_log: True


  handlers:

    - name: userlist
      lineinfile:
        create: yes
        mode: '0444'
        dest: "{{ logFile }}"
        line: "{{ results_CreateObjUser | json_query('results[*].[json]') | to_nice_json }} {{ results_CreateSecretKey | json_query('results[*].[json]') | to_nice_json }}" 
        insertafter: EOF
      failed_when: false
      delegate_to: "{{ logHost }}"
