---
- name: ECS create new NameSpace
  hosts: Dell_EMC_ECS
  gather_facts: False
  vars:
    #### add values to below variables ####
    username: ""
    password: ""
    ECS_host: ""
    nameSpace: ""
    default_vpool_rg: "" ## E.g. "urn:storageos:ReplicationGroupInfo:ec0d2999-ef3e-489b-9465-786c446434a8:global"

  tasks:

  - name: Get ECS API authentication token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
    #no_log: True

  - name: Connect to ECS | create new namespace
    uri:
      validate_certs: no
      url: https://{{ECS_host}}/object/namespaces/namespace.json
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      body_format: json
      body:
        {
          namespace: "{{ nameSpace }}",
          default_data_services_vpool: "{{ default_vpool_rg }}"
        }
      return_content: yes
    register: results_CreateNameSpace
    failed_when: default_vpool_rg == "" or nameSpace == ""
    changed_when:  results_CreateNameSpace.status == 200

  - name: Logout ECS API token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      #url: https://{{ECS_host}}/logout?force=true
      url: https://{{ECS_host}}/logout
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      return_content: yes
    register: results_logout
